{% set name = "reconciliation" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reconciliation-{{ version }}.tar.gz
  sha256: dff957d969737dec09d025c15d2cbf4f0854cd2863e1736a9fd2919fa501501f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flask ==2.0.2
    - flask-jsonpify ==1.5.0
    - marshmallow ==3.14.1

test:
  imports:
    - reconciliation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/preftech/reconciliation
  summary: An OpenRefine Reconciliation Framework for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - HeavyTony2
